#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a formatted manner

IFS=":"
while read -r username password uid gid fullname home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd
