#!/usr/bin/env bash
# Manage a process that keeps running in the background

case "$1" in
    start)
        echo "Starting the process..."
        echo $$ > /var/run/my_process.pid
        while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done &
        ;;
    stop)
        echo "Stopping the process..."
        rm /var/run/my_process.pid
        ;;
    restart)
        echo "Restarting the process..."
        rm /var/run/my_process.pid
        echo $$ > /var/run/my_process.pid
        while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done &
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
