#!/usr/bin/env bash
# This script creates a PID file and reacts to certain signals in a friendly way

echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM
