#!/usr/bin/env bash
# Manage a process that keeps running in the background

start () {
    if [ ! -f /var/run/my_process.pid ]; then
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"               
    else
        echo "manage_my_process is already running."
    fi
}

stop () {
    if [ -f /var/run/my_process.pid ]; then
        pkill -F /var/run/my_process.pid
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"               
    else
        echo "PID file does not exist. Process may not be running."
    fi
}

restart () {
    if [ -f /var/run/my_process.pid ]; then
        pkill -F /var/run/my_process.pid
        rm -f /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"             
}

case "$1" in
  start) start ;;
  stop)  stop ;;
  restart) restart ;;
  *) echo "Usage: manage_my_process {start|stop|restart}"                                           
     ;;
esac
